version: '3.8'

services:
  postgres:
    container_name: express-postgres
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: express
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5444:5432